### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by stdroniv** [stdroniv/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by TestAccountForCollab** [comment]
Contact information
* [Instagram](https://www.instagram.com/st.droniv/)
* [Telegram](https://t.me/s_droniv)
* [VK](https://vk.com/id194113640)
