### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by stdroniv** [stdroniv/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by TestAccountForCollab** [comment]
* Born in 22.04.2002
* Primary school - 2008 - 2019
* Some personal prizes 
   * 2012 - 1rst place in a regional U-12 football tournament
   * 2014 - 1rst place in Taekwondo tournament
   * 2017 winner of regional mathematics school olympiad 
   * 2018 - 2nd, 2nd, and 1rst places at three different football tournaments
* 2019 - 2023 - studying at National University Lviv Polytechnic 
* 2021 - first training certificate by Stepik Academy, Golang courses.
