### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by stdroniv** [stdroniv/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by TestAccountForCollab** [comment]
He is a great fan of cinema arts, especially Quentin Tarantino, Christopher Nolan, and Guy Ritchie films. He also loves to listen to music, but he hasn't favored genre. Friendly, funny, and ready to study. The most unloved trait in people is contempt. He isn't afraid of difficulties and ready to fail. Favorite quote:
> There are no lethal substances. There are only lethal doses.
